version: '3.8'

services:
  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=world
    ports:
      - "5432:5432"
    networks:
      - my-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge